"""init

Revision ID: 01876cf4ea56
Revises: 343fe6bf13d7
Create Date: 2025-02-11 17:33:51.851147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01876cf4ea56'
down_revision: Union[str, None] = '343fe6bf13d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_invitations_short_name', table_name='invitations')
    op.drop_column('invitations', 'short_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitations', sa.Column('short_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_invitations_short_name', 'invitations', ['short_name'], unique=True)
    # ### end Alembic commands ###
