"""init

Revision ID: 343fe6bf13d7
Revises: 8f92e5266676
Create Date: 2025-02-11 17:31:26.063713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '343fe6bf13d7'
down_revision: Union[str, None] = '8f92e5266676'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('game_game_questions_uq', 'game_answers', ['game_id', 'quiz_question_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('game_game_questions_uq', 'game_answers', type_='unique')
    # ### end Alembic commands ###
