"""init

Revision ID: 933b8cebdb54
Revises: 9b4a498ec901
Create Date: 2025-01-19 22:21:38.943463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '933b8cebdb54'
down_revision: Union[str, None] = '9b4a498ec901'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('games', 'quiz_result_copy')
    op.alter_column('quiz_question_answers', 'points',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quiz_question_answers', 'points',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.add_column('games', sa.Column('quiz_result_copy', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('games', 'result')
    # ### end Alembic commands ###
