"""init

Revision ID: 9b4a498ec901
Revises: e3838727c49c
Create Date: 2025-01-19 17:21:57.965372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b4a498ec901'
down_revision: Union[str, None] = 'e3838727c49c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_answers', sa.Column('quiz_question_id', sa.UUID(), nullable=True))
    op.add_column('game_answers', sa.Column('quiz_question_answer_id', sa.UUID(), nullable=True))
    op.drop_constraint('game_answers_quiz_answer_id_fkey', 'game_answers', type_='foreignkey')
    op.create_foreign_key(None, 'game_answers', 'quiz_questions', ['quiz_question_id'], ['id'])
    op.create_foreign_key(None, 'game_answers', 'quiz_question_answers', ['quiz_question_answer_id'], ['id'])
    op.drop_column('game_answers', 'quiz_answer_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_answers', sa.Column('quiz_answer_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'game_answers', type_='foreignkey')
    op.drop_constraint(None, 'game_answers', type_='foreignkey')
    op.create_foreign_key('game_answers_quiz_answer_id_fkey', 'game_answers', 'quiz_question_answers', ['quiz_answer_id'], ['id'])
    op.drop_column('game_answers', 'quiz_question_answer_id')
    op.drop_column('game_answers', 'quiz_question_id')
    # ### end Alembic commands ###
