"""init

Revision ID: b69724b38838
Revises: 570d3ea40ff1
Create Date: 2025-02-11 17:23:16.362834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b69724b38838'
down_revision: Union[str, None] = '570d3ea40ff1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_invitations_game_id', table_name='invitations')
    op.drop_index('ix_invitations_short_name', table_name='invitations')
    op.drop_table('invitations')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invitations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('short_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('game_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('click_counter', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name='invitations_game_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='invitations_pkey')
    )
    op.create_index('ix_invitations_short_name', 'invitations', ['short_name'], unique=False)
    op.create_index('ix_invitations_game_id', 'invitations', ['game_id'], unique=False)
    # ### end Alembic commands ###
