"""init

Revision ID: befd6ef05d45
Revises: 933b8cebdb54
Create Date: 2025-01-19 22:33:31.796885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'befd6ef05d45'
down_revision: Union[str, None] = '933b8cebdb54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizes', sa.Column('point_keys', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('quizes', 'point_fields')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizes', sa.Column('point_fields', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('quizes', 'point_keys')
    # ### end Alembic commands ###
