"""init

Revision ID: d429d619eaca
Revises: 434bad0c499a
Create Date: 2025-01-19 10:47:20.974310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd429d619eaca'
down_revision: Union[str, None] = '434bad0c499a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('session_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_games_session_id'), 'games', ['session_id'], unique=False)
    op.create_foreign_key(None, 'games', 'sessions', ['session_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.drop_index(op.f('ix_games_session_id'), table_name='games')
    op.drop_column('games', 'session_id')
    # ### end Alembic commands ###
