"""init

Revision ID: e3838727c49c
Revises: 6fbd75adf315
Create Date: 2025-01-19 17:10:11.287574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3838727c49c'
down_revision: Union[str, None] = '6fbd75adf315'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('current_quiz_question_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_games_current_quiz_question_id'), 'games', ['current_quiz_question_id'], unique=False)
    op.create_foreign_key(None, 'games', 'quiz_questions', ['current_quiz_question_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.drop_index(op.f('ix_games_current_quiz_question_id'), table_name='games')
    op.drop_column('games', 'current_quiz_question_id')
    # ### end Alembic commands ###
